<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.security.request_matcher.00qF1Z7' shared service.

return $this->privates['.security.request_matcher.00qF1Z7'] = new \Symfony\Component\HttpFoundation\RequestMatcher('^/');
