<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZVIWTy3\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZVIWTy3/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZVIWTy3.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZVIWTy3\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZVIWTy3\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ZVIWTy3',
    'container.build_id' => '01632680',
    'container.build_time' => 1539717992,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZVIWTy3');
